### PR TITLE
Try to fix for atk4/data 1.4.1

### PR DESCRIPTION
**Pull request by abbadon1334**
I try to upgrade to 1.4.1, i arrive at a point where i get some "errors" that are related to expression quoting in atk4/dsql.

Can someone put an eye on this, i don't want to arbitrary change the test to make it pass?

```
Failed asserting that two strings are equal.
Expected :'select sum(`cnt`) from ((select count(*) `cnt` from `invoice`) UNION ALL (select count(*) `cnt` from `payment`)) `derivedTable`'
Actual   :'select sum(cnt) from ((select count(*) `cnt` from `invoice`) UNION ALL (select count(*) `cnt` from `payment`)) `derivedTable`'
<Click to see difference>

...atk4/report/tests/UnionExprTest.php:97
```

### CODE REVIEW

**Comment by abbadon1334** [comment]
i add split phpunit sqlite + phpunit mysql and add travis file, @romaninsh can you activate CI to this repo?

**Comment by romaninsh** [comment]
@PhilippGrashoff Me or @DarkSide666  should look into this.

**Comment by DarkSide666** [comment]
https://github.com/atk4/report/pull/31 should go in first and then see what good we can take from this PR in.

**Comment by DarkSide666** [comment]
This issue and  few others are fixed in https://github.com/atk4/report/pull/31.
Currently tests run fine on MySQL. I didn't test on other persistences, because they will use different escaping symbol and then we will need to fix tests (replace hard-coded escaping symbol to one from persistence).

**Comment by abbadon1334** [comment]
i close this for now, if needed we can reopen it

**Pull request closed without merging**
